name: Démonstration Pipeline CI

on:
  push:
    branches:
      - main
jobs:
  demo:
    name: Jobs Demo
    runs-on: ubuntu-latest
    steps:
      - name: Première étape
        run: echo Hello!

      - name: Script plus complexe
        run: |
          echo "Début du script"
          echo "Étape 1: Clone le dépôt"
test:
  runs-on: ubuntu-latest
  steps:
    - name: Récupération code source
      users: actions/checkout@v4
    - name: Etape 2
        run: |
           echo "Étape 2: Exécute les tests"
